In [1]:
import numpy as np
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float) # two inputs [sleep, study]
y = np.array(([92], [86], [89]), dtype=float) # one output [Expected & in Exams] X = X/np.amax (X, axis=0) # maximum of X array longitudinally
y = y/100

In [2]:
#Variable initialization
epoch=5000
#Setting training iterations
lr=0.1
inputlayer_neurons = 2
hiddenlayer_neurons = 3
output_neurons = 1

In [5]:
#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons, hiddenlayer_neurons)) #weight of the link from 
bh=np.random.uniform(size=(1,hiddenlayer_neurons)) # bias of the link from input node to hidd
wout=np.random.uniform(size=(hiddenlayer_neurons, output_neurons)) #weight of the link from hi
bout=np.random.uniform(size=(1,output_neurons)) #bias of the link from hidden node to output

In [6]:
#Sigmoid Function
def sigmoid (x): return 1/(1 + np.exp(-x))
#Derivative of Sigmoid Function
def derivatives_sigmoid(x):return x * (1 - x)

In [7]:
#draws a random range of numbers uniformly of dim x*y
for i in range (epoch):
#Forward Propogation
    hinp1=np.dot (X,wh)
    hinp=hinp1 + bh
    hlayer_act=sigmoid (hinp)
    outinp1=np.dot (hlayer_act, wout)
    outinp=outinp1+ bout
    output=sigmoid (outinp)
#Backpropagation
    EO=y-output
    outgrad=derivatives_sigmoid(output)
    d_output = EO* outgrad
    EH = d_output.dot(wout.T)

In [10]:
#how much hidden layer weights contributed to error
hiddengrad=derivatives_sigmoid (hlayer_act)
d_hiddenlayer=EH*hiddengrad
#dotproduct of nextlayererror and currentlayerop
wout +=hlayer_act.T.dot(d_output) *lr
wh +=X.T.dot(d_hiddenlayer) *lr
print("Input: \n" + str(X))
print("Actual Output: \n" + str(y))
print("Predicted Output: \n",output)

Input: 
[[2. 9.]
 [1. 5.]
 [3. 6.]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.88795537]
 [0.88680316]
 [0.88781013]]
